<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8"><title>Purchase Order</title>
<style>
@page{margin:7mm 10mm 6mm}body{margin:0;color:#000;font-family:Arial,Helvetica,sans-serif;font-size:9.4px;line-height:1.28}table{width:100%;border-collapse:collapse}td,th{vertical-align:top}.right{text-align:right}.center{text-align:center}.bold{font-weight:bold}.header td{vertical-align:middle}.logo{width:72px}.company{font-size:13px;font-weight:bold}.branch{padding-left:8px;font-size:11px}.address{padding-top:4px;font-size:8.5px}.contact{margin-top:6px;font-size:8px}.doc-block{text-align:right}.barcode-space{height:25px;padding-top:3px;text-align:center;border-top:1px solid #000;letter-spacing:1px;font-weight:bold}.page-line{margin-top:1px;font-size:8px}.page-line span{margin-left:12px}.qr{width:48px;height:48px;margin-top:5px}.title{margin:2px 0 4px;text-align:center;font-size:14px;font-weight:normal}.rule{border-top:1px dotted #555}.details{margin-top:2px}.details td{padding:1.4px 2px}.label{width:13%;white-space:nowrap}.colon{width:2%;text-align:center}.left-value{width:39%}.right-label{width:13%;white-space:nowrap}.items{margin-top:5px}.items th{padding:3px;border-top:1px dotted #555;border-bottom:1px dotted #555;font-weight:normal;text-align:left}.items td{padding:4px 3px 1px}.items .num{text-align:right}.watermark-area{height:176px;text-align:center}.watermark{width:365px;height:175px}.summary{border-top:1px dotted #555;border-bottom:1px dotted #555}.summary td{padding:5px 3px}.sum-label{width:78%}.sum-colon{width:3%;text-align:center}.sum-value{text-align:right;font-weight:bold}.remark td{padding:4px 3px}.signatures{margin-top:34px;border:1px dotted #555}.signatures td{width:33.33%;border-right:1px dotted #555;padding:4px}.signatures td:last-child{border-right:0}.sign-line{border-bottom:1px dotted #555}.sign-row{margin-bottom:5px;font-size:8px}.approval-note{padding-top:3px;text-align:right;font-size:7px}.footer{margin-top:5px;font-size:8.5px}
</style></head><body>
<table class="header"><tr><td width="15%"><img class="logo" src="{{ public_path('image/background_img/finallogo.png') }}" alt="PRO 1"></td><td width="65%"><div><span class="company">PRO 1 GLOBAL COMPANY LIMITED</span><span class="branch">Lanthit</span></div><div class="address">No.76, Lanthit Street, Near Arleing Ngar Sint Pagoda, Insein Township, Yangon, Myanmar</div><table class="contact"><tr><td width="12%">Tel.</td><td width="58%">01-9640100, 9640110, 647730, 644832</td><td width="10%">Fax</td><td width="20%">Tax ID</td></tr></table></td><td width="20%" class="doc-block"><div class="barcode-space">PO-LAN1260824-001</div><div class="page-line">Pages <span>1/1</span></div>
<img class="qr" src="{{ public_path('image/po-qr-placeholder.svg') }}" alt="QR code placeholder"></td></tr></table>
<div class="title">Purchase Order (PO)</div><div class="rule"></div>
<table class="details">
<tr><td class="label">Vendor Code</td><td class="colon">:</td><td class="left-value">Z-0002</td><td class="right-label">Doc.No.</td><td class="colon">:</td><td>POLAN1260824-001</td></tr>
<tr><td class="label">Vendor Name</td><td class="colon">:</td><td class="left-value bold">LULAT TOOLS COMPANY LIMITED</td><td class="right-label">Doc.Date</td><td class="colon">:</td><td>24/08/2026</td></tr>
<tr><td class="label">Address</td><td class="colon">:</td><td class="left-value">NO.(21), Ground Flour, Shwedagon Pagoda Road. . . . .</td><td class="right-label">PR Doc.No.</td><td class="colon">:</td><td></td></tr>
<tr><td></td><td></td><td></td><td class="right-label">PR Approval<br>Date</td><td class="colon">:</td><td></td></tr>
<tr><td class="label">Tel.</td><td class="colon">:</td><td class="left-value">095163653,0973097377</td><td class="right-label">Credit Day</td><td class="colon">:</td><td>14</td></tr>
<tr><td class="label">Fax</td><td class="colon">:</td><td class="left-value">-</td><td class="right-label">Delivery Date</td><td class="colon">:</td><td></td></tr></table>
<table class="items"><thead><tr><th width="5%">No.</th><th width="16%">Product Code</th><th width="26%">ProductName</th><th width="9%" class="right">Quantity</th><th width="6%">Unit</th><th width="14%" class="right">Price</th><th width="11%" class="right">Discount</th><th width="13%" class="right">Amount</th></tr></thead><tbody>
<tr><td>1</td><td>2000000312774</td><td>ZM Spanner 8x10mm</td><td class="num">10.00</td><td>PC</td><td class="num">10,400.00</td><td class="num">0.00</td><td class="num">104,000.00</td></tr>
<tr><td>2</td><td>2000000312798</td><td>ZM Spanner 12x14mm</td><td class="num">10.00</td><td>PC</td><td class="num">14,400.00</td><td class="num">0.00</td><td class="num">144,000.00</td></tr>
<tr><td>3</td><td>2000000312804</td><td>ZM Spanner 14x17mm</td><td class="num">10.00</td><td>PC</td><td class="num">17,000.00</td><td class="num">0.00</td><td class="num">170,000.00</td></tr>
<tr><td>4</td><td>1101110021002</td><td>BL L Key star No.578</td><td class="num">6.00</td><td>PC</td><td class="num">18,000.00</td><td class="num">0.00</td><td class="num">108,000.00</td></tr></tbody></table>
<div class="watermark-area"><img class="watermark" src="{{ public_path('image/po-watermark.svg') }}" alt=""></div>
<table class="summary"><tr><td class="sum-label">Amount</td><td class="sum-colon">:</td><td class="sum-value">526,000.00</td></tr><tr><td>Product Discount (Amount)</td><td class="sum-colon">:</td><td class="sum-value">0.00</td></tr><tr><td>Base Amount</td><td class="sum-colon">:</td><td class="sum-value">526,000.00</td></tr><tr><td>Tax Amount</td><td class="sum-colon">:</td><td class="sum-value">0.00</td></tr><tr><td>Total Net Amount</td><td class="sum-colon">:</td><td class="sum-value">526,000.00</td></tr></table>
<table class="remark"><tr><td style="width:80px">Remark</td><td style="width:9px">:</td><td>Stock Refill</td></tr></table>
<table class="signatures"><tr><td><div class="sign-row">Recorded By : <span class="sign-line">Hnin Wai Phyo Hlaing</span></div><div class="sign-row">User ID&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;: <span class="sign-line">003-000838</span></div><div class="sign-row">PC Name&nbsp;&nbsp;&nbsp;: <span class="sign-line">PRO1MER-028</span></div><div class="sign-row">Recorded Date: <span class="sign-line">24/08/2026 10:35 AM</span></div></td><td><div class="sign-row">Checked By&nbsp;&nbsp;: <span class="sign-line">Wai Phyo Aung</span></div><div class="sign-row">User ID&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;: <span class="sign-line">001-000063</span></div><div class="sign-row">PC Name&nbsp;&nbsp;&nbsp;: <span class="sign-line">DESKTOP-PAHFRBP</span></div><div class="sign-row">Checked Date : <span class="sign-line">24/08/2026 10:47 AM</span></div></td><td><div class="sign-row">Approved By : <span class="sign-line">Wai Phyo Aung</span></div><div class="sign-row">User ID&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;: <span class="sign-line">001-000063</span></div><div class="sign-row">PC Name&nbsp;&nbsp;&nbsp;: <span class="sign-line">DESKTOP-PAHFRBP</span></div><div class="sign-row">Approved Date: <span class="sign-line">24/08/2026 10:49 AM</span></div><div class="approval-note">Approved via digital signature with authority</div></td></tr></table>
<table class="footer"><tr><td style="width:90px">Print By :</td><td class="bold">Khine Mar Htun</td><td class="right">24/08/2026 11:05</td></tr></table>
</body></html>
